import React,{useState,useEffect,createContext,useContext,useDeferredValue} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,TrainFront,CalendarDays,MapPin,ArrowRightLeft,UserRound,Menu,X,Sun,Moon,Ticket,ShieldCheck,Clock3,Wifi,Utensils,ChevronRight,IndianRupee,CreditCard,Smartphone,Landmark,CheckCircle2,Download,LogIn,BarChart3,Users,TrendingUp,Home,Heart,HelpCircle} from 'lucide-react';
import './styles.css';
import {trains} from './data/trains';
import {indianLocations} from './data/locations';
import {readStorage,writeStorage} from './context/storage';
import {fetchTrains} from './services/trainApi';

const AppContext=createContext();
function useApp(){return useContext(AppContext)}
function pageFromUrl(){const requested=new URLSearchParams(window.location.search).get('page');return requested==='confirmation'?'ticket-confirmation':requested||'login'}
function App(){const [theme,setTheme]=useState(localStorage.theme||'light');const [user,setUser]=useState(readStorage('user',null));const [bookings,setBookings]=useState(readStorage('bookings',[]));const [page,setPageState]=useState(pageFromUrl());const [search,setSearch]=useState({from:'Hyderabad',to:'Vijayawada',date:new Date().toISOString().slice(0,10),class:'3A',passengers:1});
 const setPage=nextPage=>{setPageState(nextPage);window.history.pushState({page:nextPage},'',nextPage==='login'?'/?':'/?page='+nextPage.replace('ticket-confirmation','confirmation'))};
 useEffect(()=>{const handleBack=()=>setPageState(pageFromUrl());window.addEventListener('popstate',handleBack);return()=>window.removeEventListener('popstate',handleBack)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.theme=theme},[theme]); useEffect(()=>{writeStorage('bookings',bookings)},[bookings]);
 const login=(phone,password)=>{const account=JSON.parse(localStorage.getItem('railgoAccount')||'null');if(!account||account.phone!==phone)return {ok:false,message:'No account found for this phone number. Please create an account first.'};if(account.password!==password)return {ok:false,message:'The phone number or password is incorrect.'};const u={name:account.name,phone:account.phone};setUser(u);localStorage.user=JSON.stringify(u);setPage('home');return {ok:true}};
 const createAccount=(profile)=>{const existing=JSON.parse(localStorage.getItem('railgoAccount')||'null');if(existing&&existing.phone===profile.phone)return {ok:false,message:'An account already exists for this phone number. Please sign in.'};localStorage.setItem('railgoAccount',JSON.stringify(profile));const u={name:profile.name,phone:profile.phone};setUser(u);localStorage.user=JSON.stringify(u);setPage('home');return {ok:true}};
 const logout=()=>{setUser(null);localStorage.removeItem('user');setPage('home')};
 return <AppContext.Provider value={{theme,setTheme,user,login,createAccount,logout,bookings,setBookings,page,setPage,search,setSearch}}><Header/><main>{page==='home'&&<HomePage/>}{page==='search'&&<SearchPage/>}{page==='payment'&&<PaymentPage/>}{page==='ticket-confirmation'&&<ConfirmationPage/>}{page==='cancelled'&&<Cancelled/>}{page==='bookings'&&<Bookings/>}{page==='login'&&<Login/>}{page==='analytics'&&<Analytics/>}</main><Footer/></AppContext.Provider>}
function Header(){const {theme,setTheme,user,logout,setPage}=useApp();const [open,setOpen]=useState(false);return <header className="header"><div className="nav wrap"><button className="brand" onClick={()=>setPage('home')}><span className="brandIcon"><TrainFront size={21}/></span>Rail<span>Go</span></button><nav className={open?'mobileOpen':''}><button onClick={()=>{setPage('home');setOpen(false)}}>Home</button><button onClick={()=>{setPage('search');setOpen(false)}}>Search Trains</button><button onClick={()=>{setPage('bookings');setOpen(false)}}>My Bookings</button><button onClick={()=>{setPage('analytics');setOpen(false)}}>Analytics</button></nav><div className="navActions"><button className="iconBtn" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={19}/>:<Sun size={19}/>}</button>{user?<button className="userBtn" onClick={logout}><UserRound size={17}/>{user.name.split(' ')[0]}</button>:<button className="loginBtn" onClick={()=>setPage('login')}><LogIn size={17}/>Login</button>}<button className="menuBtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div></header>}
function HomePage(){const {search,setSearch,setPage}=useApp();return <><section className="hero"><div className="heroBg"></div><div className="wrap heroContent"><div className="eyebrow"><span>✦</span> Smart journeys. Simple bookings.</div><h1>Travel farther,<br/><em>book smarter.</em></h1><p>Find trains, compare fares, pay securely and keep every ticket in one place.</p><SearchBox search={search} setSearch={setSearch} onSearch={()=>setPage('search')}/><div className="trust"><span><ShieldCheck size={16}/> Secure payments</span><span><Clock3 size={16}/> Instant confirmation</span><span><Ticket size={16}/> Digital tickets</span></div></div></section><section className="section wrap"><div className="sectionHead"><div><span className="kicker">WHY RAILGO</span><h2>Everything you need for a smoother journey.</h2></div><button className="textBtn" onClick={()=>setPage('search')}>Explore trains <ChevronRight size={17}/></button></div><div className="featureGrid"><Feature icon={<Search/>} title="Smart search" text="Compare schedules, classes and live seat availability in one view."/><Feature icon={<ShieldCheck/>} title="Secure checkout" text="A clean, multi-step payment experience with protected booking data."/><Feature icon={<Ticket/>} title="Digital tickets" text="Access your PNR, passenger details and journey information anytime."/></div></section><section className="stats"><div className="wrap statsGrid"><Stat n="2,400+" t="Daily services"/><Stat n="98.7%" t="Booking success"/><Stat n="4.9/5" t="Traveller rating"/><Stat n="24/7" t="Support"/></div></section><section className="section wrap routes"><div className="sectionHead"><div><span className="kicker">POPULAR ROUTES</span><h2>Where are you heading next?</h2></div></div><div className="routeGrid"><Route from="Hyderabad" to="Vijayawada" fare="From ₹480" onClick={()=>{setSearch({...search,from:'Hyderabad',to:'Vijayawada'});setPage('search')}}/><Route from="Chennai" to="Bengaluru" fare="From ₹620"/><Route from="Mumbai" to="Pune" fare="From ₹390"/></div></section></>}
function SearchBox({search,setSearch,onSearch}){return <div className="searchBox"><div className="field"><MapPin/><label>From<input list="indian-locations" value={search.from} onChange={e=>setSearch({...search,from:e.target.value})}/></label></div><button className="swap" onClick={()=>setSearch({...search,from:search.to,to:search.from})}><ArrowRightLeft size={17}/></button><div className="field"><MapPin/><label>To<input list="indian-locations" value={search.to} onChange={e=>setSearch({...search,to:e.target.value})}/></label></div><datalist id="indian-locations">{indianLocations.map(location=><option value={location} key={location}/>)}</datalist><div className="field"><CalendarDays/><label>Journey date<input type="date" value={search.date} onChange={e=>setSearch({...search,date:e.target.value})}/></label></div><div className="field smallField"><Users/><label>Travelers<select value={search.passengers} onChange={e=>setSearch({...search,passengers:Number(e.target.value)})}>{Array.from({length:10},(_,index)=><option value={index+1} key={index+1}>{index+1} {index===0?'traveler':'travelers'}</option>)}</select></label></div><div className="field smallField"><Ticket/><label>Class<select value={search.class} onChange={e=>setSearch({...search,class:e.target.value})}><option value="GN">General</option><option value="SL">Sleeper</option><option value="3A">AC 3 Tier</option><option value="2A">AC 2 Tier</option></select></label></div><button className="searchBtn" onClick={onSearch}><Search size={19}/> Search</button></div>}
function Feature({icon,title,text}){return <div className="feature card"><div className="featureIcon">{icon}</div><h3>{title}</h3><p>{text}</p></div>};function Stat({n,t}){return <div><strong>{n}</strong><span>{t}</span></div>};function Route({from,to,fare,onClick}){return <button className="route card" onClick={onClick}><div><b>{from}</b><ArrowRightLeft size={16}/><b>{to}</b></div><span>{fare}</span><ChevronRight/></button>}
function SearchPage(){const {search,setPage}=useApp();const deferredSearch=useDeferredValue(search);const [sort,setSort]=useState('departure');const [availableTrains,setAvailableTrains]=useState([]);const [loading,setLoading]=useState(true);useEffect(()=>{let active=true;setLoading(true);fetchTrains(deferredSearch).then(result=>{if(active){setAvailableTrains(result);setLoading(false)}});return()=>{active=false}},[deferredSearch.from,deferredSearch.to]);const sorted=[...availableTrains].sort((a,b)=>sort==='fare'?a.classes[deferredSearch.class].fare-b.classes[deferredSearch.class].fare:a.depart.localeCompare(b.depart));return <section className="section wrap searchPage"><div className="pageTitle"><div><span className="kicker">TRAIN SEARCH</span><h1>{search.from} <span>→</span> {search.to}</h1><p>{search.date} · {search.passengers} passenger · {search.class}</p></div><button className="outlineBtn" onClick={()=>setPage('home')}>Modify search</button></div><div className="resultsLayout"><aside className="filters card"><h3>Filters</h3><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="departure">Departure</option><option value="fare">Lowest fare</option></select></label><div className="filterLine"><span>Free cancellation</span><input type="checkbox"/></div><div className="filterLine"><span>Meals included</span><input type="checkbox"/></div></aside><div className="results">{loading?<div className="card loadingState">Loading trains...</div>:sorted.map(t=><TrainCard key={t.id} train={t} selectedClass={deferredSearch.class}/>)}</div></div></section>}
function TrainCard({train,selectedClass}){const {setPage,search,setSearch}=useApp();const c=train.classes[selectedClass];const fareOptions=[['2A','AC 2 Tier'],['GN','General'],['3A','AC 3 Tier'],['SL','Sleeper']];const selectClass=code=>setSearch({...search,class:code});return <div className="trainCard card"><div className="trainMain"><div className="trainName"><span className="trainLogo"><TrainFront/></span><div><h3>{train.name}</h3><small>{train.id} · Daily</small></div></div><div className="times"><div><b>{train.depart}</b><span>{train.from}</span></div><div className="duration"><i></i><small>{train.duration}</small></div><div><b>{train.arrive}</b><span>{train.to}</span></div></div><div className="tags">{train.tags.map(x=><span key={x}>{x}</span>)}</div></div><div className="trainSide"><div className="fareCompare">{fareOptions.map(([code,label])=><button type="button" className={selectedClass===code?'fareOption activeFare':'fareOption'} key={code} onClick={()=>selectClass(code)}><small>{label}</small><strong>₹{train.classes[code].fare.toLocaleString()}</strong><span>{train.classes[code].seats} seats</span></button>)}</div><div className="selectedFare"><small>Selected: {selectedClass}</small><strong>₹{c.fare.toLocaleString()}</strong><span className={c.seats<10?'low':''}>{c.seats} seats left</span></div><button className="primaryBtn" onClick={()=>setPage('payment')}>Book now <ChevronRight size={17}/></button></div></div>}
function LegacyPaymentPage(){const {search,setPage,bookings,setBookings}=useApp();const [method,setMethod]=useState('upi');const [processing,setProcessing]=useState(false);const fare=search.class==='SL'?480:search.class==='3A'?1040:1490;const total=fare*search.passengers+35;const pay=()=>{setProcessing(true);setTimeout(()=>{const b={pnr:'RG'+Math.floor(100000+Math.random()*899999),train:'Godavari Intercity',from:search.from,to:search.to,date:search.date,time:'15:40',passengers:search.passengers,class:search.class,total,status:'Confirmed'};setBookings([b,...bookings]);setPage('confirmation')},1000)};return <section className="section wrap checkout"><div className="checkoutHead"><button className="back" onClick={()=>setPage('search')}>← Back to trains</button><div className="steps"><span className="done">1 Search</span><span className="active">2 Payment</span><span>3 Confirmation</span></div></div><div className="checkoutGrid"><div><div className="card panel"><div className="panelTitle"><div><span className="kicker">PASSENGER DETAILS</span><h2>Who is travelling?</h2></div><ShieldCheck/></div><div className="passenger"><div className="avatar">AK</div><div><b>Alex Kumar</b><span>Adult · 28 years</span></div><span className="selected">Selected</span></div><div className="addPassenger">+ Add passenger</div></div><div className="card panel"><div className="panelTitle"><div><span className="kicker">PAYMENT METHOD</span><h2>Choose how to pay</h2></div></div><div className="payMethods">{[['upi',<Smartphone/>,'UPI','Google Pay, PhonePe & more'],['card',<CreditCard/>,'Card','Visa, Mastercard, RuPay'],['bank',<Landmark/>,'Net banking','All major banks']].map(([id,ic,title,sub])=><button key={id} className={method===id?'payOption selectedPay':'payOption'} onClick={()=>setMethod(id)}>{ic}<span><b>{title}</b><small>{sub}</small></span>{method===id&&<CheckCircle2/>}</button>)}</div><div className="fakeInput"><label>{method==='upi'?'UPI ID':method==='card'?'Card number':'Bank account'}</label><input placeholder={method==='upi'?'alex@upi':method==='card'?'1234 5678 9012 3456':'Select your bank'}/></div></div></div><aside className="card summary"><span className="kicker">FARE SUMMARY</span><h2>Booking total</h2><div className="journey"><b>{search.from}</b><ArrowRightLeft/><b>{search.to}</b><span>{search.date}</span></div><div className="line"><span>Base fare × {search.passengers}</span><b>₹{(fare*search.passengers).toLocaleString()}</b></div><div className="line"><span>Convenience fee</span><b>₹35</b></div><hr/><div className="total"><span>Total</span><strong>₹{total.toLocaleString()}</strong></div><button className="primaryBtn full" onClick={pay} disabled={processing}>{processing?'Processing secure payment…':<>Pay ₹{total.toLocaleString()} <ArrowRightLeft size={17}/></>}</button><p className="secure"><ShieldCheck size={15}/> 256-bit encrypted checkout</p></aside></div></section>}
function QrPaymentPage(){
 const {search,setPage,setBookings}=useApp();
 const [processing,setProcessing]=useState(false);
 const [scanned,setScanned]=useState(false);
 const [timeLeft,setTimeLeft]=useState(300);
 const fare=search.class==='GN'?190:search.class==='SL'?480:search.class==='3A'?1040:1490;
 const total=fare*search.passengers+35;
 const minutes=Math.floor(timeLeft/60);
 const seconds=timeLeft%60;

 useEffect(()=>{if(timeLeft<=0){setPage('cancelled');return}const timer=setInterval(()=>setTimeLeft(value=>Math.max(value-1,0)),1000);return()=>clearInterval(timer)},[timeLeft,setPage]);
 const qrImage=`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(`upi://pay?pa=railgo@upi&pn=RailGo&am=${total}&cu=INR`)}`;

 const completeBooking=()=>{if(timeLeft<=0||processing)return;setProcessing(true);const booking={pnr:'RG'+Math.floor(100000+Math.random()*899999),train:'Godavari Intercity',from:search.from,to:search.to,date:search.date,time:'15:40',passengers:search.passengers,class:search.class,total,status:'Confirmed'};setBookings(previous=>[booking,...previous]);setPage('ticket-confirmation')};
 const pay=()=>completeBooking();
 const confirmScan=()=>{if(timeLeft<=0||processing)return;setScanned(true);completeBooking()};

 return <section className="section wrap checkout"><div className="checkoutHead"><button className="back" onClick={()=>setPage('search')}>← Back to trains</button><div className="steps"><span className="done">1 Search</span><span className="active">2 Payment</span><span>3 Confirmation</span></div></div><div className="checkoutGrid"><div><div className="card panel"><div className="panelTitle"><div><span className="kicker">PASSENGER DETAILS</span><h2>Who is travelling?</h2></div><ShieldCheck/></div><div className="passenger"><div className="avatar">AK</div><div><b>Alex Kumar</b><span>Adult · 28 years</span></div><span className="selected">Selected</span></div></div><div className="card panel qrPanel"><div className="panelTitle"><div><span className="kicker">SCAN TO PAY</span><h2>Complete payment</h2></div><Smartphone/></div><div className={scanned?'qrBox qrVerified':'qrBox'}><img className="realQrCode" src={qrImage} alt="Payment QR code" onClick={confirmScan}/><strong>{scanned?'Payment completed':'Scan this QR code to pay'}</strong><small>{scanned?'Preparing your confirmed ticket…':'Use any trusted payment app'}</small>{!scanned&&<button className="outlineBtn" onClick={confirmScan} disabled={timeLeft<=0}>I scanned and paid</button>}</div><div className="paymentTimer"><Clock3 size={17}/><span>{timeLeft<=0?'Payment cancelled':scanned?'Payment completed':'Payment window'}</span><strong>{String(minutes).padStart(2,'0')}:{String(seconds).padStart(2,'0')}</strong></div></div></div><aside className="card summary"><span className="kicker">FARE SUMMARY</span><h2>Booking total</h2><div className="journey"><b>{search.from}</b><ArrowRightLeft/><b>{search.to}</b><span>{search.date}</span></div><div className="line"><span>Base fare × {search.passengers}</span><b>₹{(fare*search.passengers).toLocaleString()}</b></div><div className="line"><span>Convenience fee</span><b>₹35</b></div><hr/><div className="total"><span>Total</span><strong>₹{total.toLocaleString()}</strong></div><button className="primaryBtn full" onClick={pay} disabled={!scanned||processing||timeLeft<=0}>{processing?'Processing secure payment…':timeLeft<=0?'Payment cancelled':scanned?'Confirm ticket': 'Scan QR to continue'}</button><p className="secure"><ShieldCheck size={15}/> Confirmation is available only after payment is completed</p></aside></div></section>
}
function PaymentPage(){
 const {search,setSearch}=useApp();
 const [passengers,setPassengers]=useState([{name:'Alex Kumar',age:'28'}]);
 const addPassenger=()=>{const next=[...passengers,{name:'',age:''}];setPassengers(next);setSearch({...search,passengers:next.length})};
 const updatePassenger=(index,key,value)=>setPassengers(previous=>previous.map((passenger,item)=>item===index?{...passenger,[key]:value}:passenger));
 return <><div className="passengerDetails wrap"><div><span className="kicker">PASSENGER DETAILS</span><h2>Who is travelling?</h2></div><div className="passengerFields">{passengers.map((passenger,index)=><div className="passengerField" key={index}><span>{index+1}</span><input value={passenger.name} onChange={event=>updatePassenger(index,'name',event.target.value)} placeholder="Passenger name"/><input value={passenger.age} onChange={event=>updatePassenger(index,'age',event.target.value)} placeholder="Age" inputMode="numeric"/></div>)}</div><button className="addPassengerButton" onClick={addPassenger}>+ Add passenger</button></div><QrPaymentPage/></>;
}
function Cancelled(){const {setPage}=useApp();return <section className="section wrap confirmation cancelledPage"><div className="cancelIcon"><X size={48}/></div><span className="kicker">PAYMENT CANCELLED</span><h1>Booking was not completed.</h1><p>The QR payment window expired before payment was verified. No ticket was issued.</p><div className="confirmActions"><button className="primaryBtn" onClick={()=>setPage('search')}>Search trains</button><button className="outlineBtn" onClick={()=>setPage('home')}>Back to home</button></div></section>}
function ConfirmationPage(){const {bookings,setPage}=useApp();const b=bookings[0]||{pnr:'RG000000',train:'Godavari Intercity',from:'Hyderabad',to:'Vijayawada',date:'Today',time:'15:40',passengers:1,class:'3A',total:1075,status:'Confirmed'};return <section className="section wrap confirmation"><div className="successIcon"><CheckCircle2 size={48}/></div><span className="kicker">BOOKING CONFIRMED</span><h1>Your journey is ready.</h1><p>Your ticket has been confirmed successfully. Show the QR or PNR at the station when you travel.</p><div className="ticket card"><div className="ticketTop"><div><small>PNR</small><strong>{b.pnr}</strong></div><span>CONFIRMED</span></div><div className="ticketRoute"><div><small>{b.from}</small><b>{b.time}</b><span>{b.date}</span></div><div className="ticketLine"><TrainFront/><i></i><i></i><i></i></div><div><small>{b.to}</small><b>20:55</b><span>{b.class} · {b.passengers} passenger</span></div></div><div className="ticketBottom"><span><b>{b.train}</b><small>Coach allocation at charting</small></span><strong>₹{Number(b.total).toLocaleString()}</strong></div></div><div className="confirmActions"><button className="primaryBtn" onClick={()=>window.print()}><Download size={17}/> Download ticket</button><button className="outlineBtn" onClick={()=>setPage('bookings')}>View my bookings</button></div></section>}
function Bookings(){const {bookings,setPage}=useApp();return <section className="section wrap"><div className="pageTitle"><div><span className="kicker">MY TRIPS</span><h1>Your bookings</h1><p>All your upcoming and past RailGo journeys.</p></div><button className="primaryBtn" onClick={()=>setPage('search')}>Book a new trip</button></div>{bookings.length===0?<div className="empty card"><Ticket size={40}/><h2>No bookings yet</h2><p>Your confirmed tickets will appear here.</p><button className="primaryBtn" onClick={()=>setPage('search')}>Search trains</button></div>:<div className="bookingList">{bookings.map(b=><div className="booking card" key={b.pnr}><div><span className="status"><CheckCircle2 size={14}/> {b.status}</span><h3>{b.from} → {b.to}</h3><p>{b.train} · {b.date} · {b.class}</p></div><div><small>PNR</small><b>{b.pnr}</b></div><strong>₹{Number(b.total).toLocaleString()}</strong><ChevronRight/></div>)}</div>}</section>}
function Login(){
 const {login,createAccount:register}=useApp();
 const [createAccount,setCreateAccount]=useState(false);
 const [name,setName]=useState('');
 const [phone,setPhone]=useState('');
 const [password,setPassword]=useState('');
 const [confirmPassword,setConfirmPassword]=useState('');
 const [error,setError]=useState('');

 const submit=e=>{
  e.preventDefault();
  const cleanPhone=phone.replace(/\D/g,'');
  if(cleanPhone.length!==10){setError('Enter a valid 10-digit phone number.');return}
  if(password.length<6){setError('Password must be at least 6 characters.');return}
    if(createAccount&&password!==confirmPassword){setError('Passwords do not match.');return}
    const result=createAccount?register({name:name.trim()||'Alex Kumar',phone:cleanPhone,password}):login(cleanPhone,password);
    if(!result.ok){setError(result.message);if(!createAccount&&result.message.startsWith('No account found'))setCreateAccount(true)}
 };

 return <section className="loginPage"><form className="loginCard card" onSubmit={submit}><div className="brand big"><span className="brandIcon"><TrainFront/></span>Rail<span>Go</span></div><h1>{createAccount?'Create your account':'Welcome back'}</h1><p>{createAccount?'Save your journeys and manage tickets easily.':'Sign in to manage your journeys and tickets.'}</p>{createAccount&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Kumar" autoComplete="name"/></label>}<label>Phone number<div className="phoneField"><span>+91</span><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="9876543210" inputMode="numeric" autoComplete="tel" required/></div></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="At least 6 characters" minLength="6" autoComplete={createAccount?'new-password':'current-password'} required/></label>{createAccount&&<label>Confirm password<input value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} type="password" placeholder="Repeat your password" autoComplete="new-password" required/></label>}{error&&<p className="formError">{error}</p>}<button className="primaryBtn full" type="submit">{createAccount?'Create account':'Sign in'} <ArrowRightLeft size={17}/></button><button className="switchAuth" type="button" onClick={()=>{setCreateAccount(!createAccount);setError('')}}>{createAccount?'Already have an account? Sign in':'New to RailGo? Create an account'}</button><div className="demo"><ShieldCheck size={15}/> Demo mode — account details stay in this browser</div></form></section>}
function Analytics(){return <section className="section wrap"><div className="pageTitle"><div><span className="kicker">ADMIN OVERVIEW</span><h1>Booking analytics</h1><p>A sample dashboard showing reusable analytics components.</p></div></div><div className="metricGrid"><Metric icon={<Ticket/>} title="Bookings" value="12,842" delta="+18.4%"/><Metric icon={<Users/>} title="Passengers" value="28,516" delta="+12.1%"/><Metric icon={<IndianRupee/>} title="Revenue" value="₹38.4L" delta="+21.7%"/><Metric icon={<TrendingUp/>} title="Conversion" value="8.72%" delta="+2.3%"/></div><div className="chart card"><div className="panelTitle"><div><span className="kicker">WEEKLY PERFORMANCE</span><h2>Bookings & revenue trend</h2></div><BarChart3/></div><div className="bars">{[48,65,58,78,71,88,96].map((v,i)=><div key={i} style={{'--h':v+'%'}}><span></span><small>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</small></div>)}</div></div></section>}
function Metric({icon,title,value,delta}){return <div className="metric card"><div className="metricIcon">{icon}</div><span>{title}</span><strong>{value}</strong><small>{delta} vs last week</small></div>}
function Footer(){return <footer><div className="wrap footerGrid"><div><div className="brand"><span className="brandIcon"><TrainFront size={18}/></span>Rail<span>Go</span></div><p>Modern train booking for effortless journeys.</p></div><div><b>Product</b><span>Search trains</span><span>Bookings</span><span>Offers</span></div><div><b>Company</b><span>About us</span><span>Careers</span><span>Contact</span></div><div><b>Support</b><span>Help center</span><span>Cancellation</span><span>Terms & privacy</span></div></div><div className="wrap copyright">© 2026 RailGo Capstone Project · Built with React.js</div></footer>}
createRoot(document.getElementById('root')).render(<App/>);
